CAR_85_COLUMN_DESCRIPTION = {
    'symboling': 'Insurance risk rating of the vehicle, ranging from -3 (safest) to 3 (riskiest)',
    'make': 'Brand or manufacturer of the car',
    'fuel-type': 'Type of fuel the car uses, such as diesel or gasoline',
    'aspiration': 'Method of air intake for the engine, either standard or turbocharged',
    'num-of-doors': 'Number of doors the car has',
    'body-style': 'Design form of the car body, like sedan, hatchback, etc.',
    'drive-wheels': 'Type of drivetrain, indicating which wheels are powered (front, rear, or all)',
    'engine-location': 'Position of the engine in the car, either front or rear',
    'wheel-base': 'Distance between the front and rear wheels, measured in inches',
    'length': 'Overall length of the car, measured in inches',
    'width': 'Overall width of the car, measured in inches',
    'height': 'Overall height of the car, measured in inches',
    'curb-weight': 'Weight of the car without any passengers or cargo, measured in pounds',
    'engine-type': 'Configuration and design of the engine (e.g., OHC, OHCV)',
    'num-of-cylinders': 'Total number of cylinders in the engine',
    'engine-size': 'Displacement volume of the engine, measured in cubic centimeters',
    'fuel-system': 'Mechanism or system for delivering fuel to the engine (e.g., MPFI, 2bbl)',
    'bore': 'Internal diameter of each cylinder in the engine, measured in inches',
    'stroke': 'Travel distance of the piston within the engine cylinder, measured in inches',
    'compression-ratio': 'Volume ratio between piston positions at the bottom and top of its stroke',
    'horsepower': 'Engine power output, measured in horsepower',
    'peak-rpm': 'Engine speed at which maximum power output is achieved, measured in RPM',
    'city-mpg': 'Fuel efficiency during city driving, measured in miles per gallon',
    'highway-mpg': 'Fuel efficiency during highway driving, measured in miles per gallon',
    'price': 'Market price of the car, usually provided in USD',
    'price_bins': 'Categorical representation of car price for easier analysis or visualization'
}
